#!/usr/bin/bash
# rest of Mg datasets
time python3 fisherAnalysis/code/fisher.py fisherAnalysis/results/hasMetalsMg.xlsx 0.025 m 3.5 1> fisherAnalysis/results/hasMetalsMg2.5%.out 2> fisherAnalysis/results/fisher.err

time python3 fisherAnalysis/code/fisher.py fisherAnalysis/results/hasMetalsMg.xlsx 0.05 m 3.5 1> fisherAnalysis/results/hasMetalsMg5%.out 2> fisherAnalysis/results/fisher.err

time python3 fisherAnalysis/code/fisher.py fisherAnalysis/results/hasMetalsMg.xlsx 0.1 m 3.5 1> fisherAnalysis/results/hasMetalsMg10%.out 2> fisherAnalysis/results/fisher.err

# topsix datasets
time python3 fisherAnalysis/code/getHasMetals.py results/standalone_01-04-22.txt results/standalone_01-04-22 fisherAnalysis/results/hasMetalsTopSix.txt ZN,MG,CA,FE,NA,MN 1> fisherAnalysis/results/fisher.out 2> fisherAnalysis/results/fisher.err

time python3 fisherAnalysis/code/getResults.py fisherAnalysis/results/hasMetalsTopSix.txt hasMetalsTopSix m

time python3 fisherAnalysis/code/fisher.py fisherAnalysis/results/hasMetalsTopSix.xlsx 0.01 m 3.5 1> fisherAnalysis/results/hasMetalsTopSix1%.out 2> fisherAnalysis/results/fisher.err

time python3 fisherAnalysis/code/fisher.py fisherAnalysis/results/hasMetalsTopSix.xlsx 0.025 m 3.5 1> fisherAnalysis/results/hasMetalsTopSix2.5%.out 2> fisherAnalysis/results/fisher.err

time python3 fisherAnalysis/code/fisher.py fisherAnalysis/results/hasMetalsTopSix.xlsx 0.05 m 3.5 1> fisherAnalysis/results/hasMetalsTopSix5%.out 2> fisherAnalysis/results/fisher.err

time python3 fisherAnalysis/code/fisher.py fisherAnalysis/results/hasMetalsTopSix.xlsx 0.1 m 3.5 1> fisherAnalysis/results/hasMetalsTopSix10%.out 2> fisherAnalysis/results/fisher.err

# all datasets
time python3 fisherAnalysis/code/getHasMetals.py results/standalone_01-04-22.txt results/standalone_01-04-22 fisherAnalysis/results/hasMetalsAll.txt ZN,MG,CA,FE,NA,MN,K,CU,NI,CO,CD,HG,PT,MO,AL,V,BA,SR,RU,CS,W,YB,AU,Y,LI,PB,GD,TL,RB,SM,IR,PR,RH,EU,PD,AG,OS,LU,HO,TB,CR,GA,LA,SB,CE,ER,IN,BI,DY,BE,ZR,SN,HF,TA,RE,PA,U 1> fisherAnalysis/results/fisher.out 2> fisherAnalysis/results/fisher.err

time python3 fisherAnalysis/code/getResults.py fisherAnalysis/results/hasMetalsAll.txt hasMetalsAll m

time python3 fisherAnalysis/code/fisher.py fisherAnalysis/results/hasMetalsAll.xlsx 0.01 m 3.5 1> fisherAnalysis/results/hasMetalsAll1%.out 2> fisherAnalysis/results/fisher.err

time python3 fisherAnalysis/code/fisher.py fisherAnalysis/results/hasMetalsAll.xlsx 0.025 m 3.5 1> fisherAnalysis/results/hasMetalsAll2.5%.out 2> fisherAnalysis/results/fisher.err

time python3 fisherAnalysis/code/fisher.py fisherAnalysis/results/hasMetalsAll.xlsx 0.05 m 3.5 1> fisherAnalysis/results/hasMetalsAll5%.out 2> fisherAnalysis/results/fisher.err

time python3 fisherAnalysis/code/fisher.py fisherAnalysis/results/hasMetalsAll.xlsx 0.1 m 3.5 1> fisherAnalysis/results/hasMetalsAll10%.out 2> fisherAnalysis/results/fisher.err

echo "Finished the rest of hasMetals!"
